config/routes.rb
Rails.application.routes.draw do
  get 'foursquare_locations/request_location'
  get 'foursquare_locations/fetch_items_and_save'
  put 'foursquare_locations/fetch_items_and_save'

  get 'system/unsubscribe', as: 'unsubscribe'
  get 'system/about_us', as: 'about_us'
  get 'system/privacy_policy', as: 'privacy_policy'
  get 'system/terms_of_use', as: 'terms_of_use'
  get 'system/contact_us', as: 'contact_us'
  get 'system/faq', as: 'faq'

  class IsJson
    def self.matches?(request)
      request.format.present? && request.format.symbol == :json
    end
  end

  devise_for :users, class_name: "User", :controllers => { omniauth_callbacks: 'omniauth_callbacks'}

  devise_scope :user do
    get "/authentication", to: 'devise/sessions#new'
  end

  namespace :api do
    namespace :v1, defaults: {format: 'json'}, constraints: IsJson do
      namespace :auth do
        devise_for :users,
        class_name: "User",
        :controllers => {
          sessions: 'api/v1/auth/sessions',
          registrations: 'api/v1/auth/registrations',
          passwords: 'api/v1/auth/passwords',
          unlocks: 'api/v1/auth/unlocks',
          confirmations: 'api/v1/auth/confirmations'
        }
      end

      resources :users
      resources :user_devices
    end
  end

  devise_scope :user do
    post "api/v1/auth/users/password/update", to: "api/v1/auth/passwords#update"
    post "api/v1/auth/users/update", to: "api/v1/auth/registrations#update"
  end

  scope "/:section/:subsection/:current_account_id", defaults: {section: 'home', subsection: 'main', current_account_id: '0' } do
    mount RailsAdmin::Engine => '/ra', as: 'rails_admin'
  end

  get "latest_adverts", to: "home#index",  constraints: { format: 'json'}

  authenticated :user do
    get "/", to: "home#index"
    get "/forwarder", to: "home#fowarder", as: :fowarder
  end

  devise_scope :user do
    root to: 'devise/sessions#new'
  end

end

app/controllers/foursquare_locations_controller.rb
class FoursquareLocationsController < ApplicationController
  def request_location
  end

  def fetch_items_and_save
    max_timestamp = Time.zone.now
    number_of_pages = 20
    begin
      @ins = InstagramItem.instagram_items(max_timestamp: max_timestamp,
                                   max_number_of_pages: number_of_pages,
                                   :latitude => params[:lat],:longitude =>params[:long])
    rescue => e
      flash[:alert] = "Encountered an error when trying to fetch Instagram Item error: #{e.message}"
      @error = true
    end

    unless @ins.present?
      render :request_location
    else
      flash[:notice] = "Instagram Item has been successfully created."
      redirect_to main_app.fowarder_path(fowarder: {action: 'index',model_name: 'instagram_item', section: 'instagram_items', subsection: 'main'})
    end

  end

end

app/helpers/foursquare_locations_helper.rb
module FoursquareLocationsHelper
end

app/views/foursquare_locations/request_location.html.erb
<html>
<head>
<meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
<script type="text/javascript" src="https://maps.google.com/maps/api/js?sensor=false&key=AIzaSyAXs4SJEF5yJWXA5otozxLEylcNkOrf_Kg"></script>
<script type="text/javascript">
var geocoder = new google.maps.Geocoder();
// AIzaSyAXs4SJEF5yJWXA5otozxLEylcNkOrf_Kg

function geocodePosition(pos) {
  geocoder.geocode({
    latLng: pos
  }, function(responses) {
    if (responses && responses.length > 0) {
      updateMarkerAddress(responses[0].formatted_address);
    } else {
      updateMarkerAddress('Cannot determine address at this location.');
    }
  });
}


function updateMarkerStatus(str) {
  document.getElementById('markerStatus').innerHTML = str;
}


function updateMarkerPosition(latLng) {

  document.getElementById('info').innerHTML = [
    latLng.lat(),
    latLng.lng()
  ].join(', ');
  document.getElementById('long').value = latLng.lng();
  document.getElementById('lat').value = latLng.lat();
}


function updateMarkerAddress(str) {
  document.getElementById('address').innerHTML = str;
}

function success(position)
{
    document.getElementById('long').value = position.coords.longitude;
    document.getElementById('lat').value = position.coords.latitude
    // var latLng = new google.maps.LatLng(-34.397, 150.644);
    var lat = position.coords.latitude
    var long = position.coords.longitude
    // var latLng = new google.maps.LatLng(-25.7589728,28.1919346)
    var latLng = new google.maps.LatLng(lat,long)

    var map = new google.maps.Map(document.getElementById('mapCanvas'), {
      zoom: 17,
      center: latLng,
      mapTypeId: google.maps.MapTypeId.ROADMAP
    });
    var marker = new google.maps.Marker({
      position: latLng,
      title: 'Point A',
      map: map,
      draggable: true
    });


    // Update current position info.
    updateMarkerPosition(latLng);
    geocodePosition(latLng);


    // Add dragging event listeners.
    google.maps.event.addListener(marker, 'dragstart', function() {
      updateMarkerAddress('Dragging...');
    });


    google.maps.event.addListener(marker, 'drag', function() {
      updateMarkerStatus('Dragging...');
      updateMarkerPosition(marker.getPosition());
    });


    google.maps.event.addListener(marker, 'dragend', function() {
      updateMarkerStatus('Drag ended');
      geocodePosition(marker.getPosition());
    });

}

function fail()
{
   // Could not obtain location
}
function initialize() {

  if( navigator.geolocation )
  {
     // Call getCurrentPosition with success and failure callbacks
     navigator.geolocation.getCurrentPosition( success, fail );
  }
  else
  {
     alert("Sorry, your browser does not support geolocation services.");
  }

}


// Onload handler to fire off the app.
google.maps.event.addDomListener(window, 'load', initialize);
</script>
</head>
<body>
  <style>
  #mapCanvas {
    width: 700px;
    height: 500px;
    float: left;
  }
  #infoPanel {
    float: left;
    margin-left: 10px;
  }
  #infoPanel div {
    margin-bottom: 5px;
  }
  </style>


  <div id="mapCanvas"></div>
  <div id="infoPanel">
    <b>Marker status:</b>
    <div id="markerStatus"><i>Click and drag the marker.</i></div>
    <b>Current position:</b>
    <div id="info"></div>
    <b>Closest matching address:</b>
    <div id="address"></div>
    <br/><br/>
    <%= form_for(InstagramItem.new,url: foursquare_locations_fetch_items_and_save_path(), :html => {method: 'put', :role => 'form', class: "margin-bottom-0"}) do |f| %>
      <INPUT TYPE="hidden" NAME="lat" ID="lat" VALUE="">
      <INPUT TYPE="hidden" NAME="long" ID="long" VALUE="">
      <div class="login-buttons">
        <%= html_submit(content=fa_icon('user-plus', :text => "Generate Instagram Item & Save"), extra={class: "btn btn-primary"}) %>
      </div>

    <%end%>
  </div>
</body>
</html>